name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyautogui pillow requests mss pyinstaller opencv-python numpy
        
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name=AI-Game-Assistant main_enhanced.py
        
    - name: List files in dist
      shell: bash
      run: |
        echo "Files in dist directory:"
        ls -la dist/
        
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: AI-Game-Assistant-Windows
        path: dist/AI-Game-Assistant.exe
        if-no-files-found: warn
        retention-days: 30
