name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyautogui pillow requests mss pyinstaller opencv-python numpy
        
    - name: List files before build
      run: |
        echo "Current directory contents:"
        dir
        
    - name: Build executable
      run: |
        echo "Building with PyInstaller..."
        pyinstaller --onefile --windowed --name="AI-Game-Assistant" main_enhanced.py
        echo "Build completed, checking dist folder:"
        dir dist
        
    - name: List all generated files
      run: |
        echo "All files in dist folder:"
        dir dist /s
        if exist "dist\AI-Game-Assistant.exe" (
          echo "Found AI-Game-Assistant.exe"
        ) else (
          echo "AI-Game-Assistant.exe not found"
        )
        
    - name: Upload executable (try multiple patterns)
      uses: actions/upload-artifact@v4
      with:
        name: AI-Game-Assistant-Windows
        path: |
          dist/*.exe
          dist/AI-Game-Assistant.exe
          dist/AI-Game-Assistant-Enhanced.exe
        if-no-files-found: warn
        retention-days: 30
